name: Test Sem

on:
  push:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: print pwd
        run: pwd
      - name: cd and print in parent
        run: |
          cd ..
          pwd
          ls -la
      - name: print pwd
        run: pwd
