name: Test Sem

on:
  push:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: print pwd
        run: pwd
      - name: cd ..
        run: cd ..
      - name: print pwd
        run: pwd
